config/routes.rb
Rails.application.routes.draw do

  get 'pages/privacypolicy'

  get 'previews/demo'

  root to: 'pages#home'

  mount Attachinary::Engine => "/attachinary"

  resources :profiles, except: [:destroy ]

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  resources :companies do
    resources :campaigns do
      post "/create_facebook_campaign",  to: "campaigns#create_facebook_campaign", as: "create_facebook"
      post "/create_facebook_adset", to: "campaigns#create_facebook_adset", as: "create_adset"
      resources :ads do
        post "create_facebook_ad", to: "ads#create_facebook_ad", as: "create_ad"
      end

    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/profile.rb
class Profile < ApplicationRecord
  has_attachment  :avatar, accept: [:jpg, :png, :gif]
  belongs_to :user
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update]

  def show

  end

  def new
    @profile = Profile.new
  end

  def create
    @profile = Profile.new(profile_params)
    @profile.user = current_user
    if @profile.save
      redirect_to '/'
    else
      redirect_to :new
    end
  end

  def update
    @profile.update(profile_params)
    redirect_to profile_path(@profile)
  end

  def edit
  end

  private

  def set_profile
   @profile = Profile.find_by(user: current_user)
  end

  def profile_params
    params.require(:profile).permit(:first_name, :last_name, :street, :street_number, :zip_code, :city, :avatar, :country)
  end
end

app/views/profiles/_form.html.erb
<h4>Please enter the needed information to <%= profile_message %></h4>

<%= simple_form_for [@profile] do |f| %>
 <%= f.input :first_name, placeholder: 'First name', label: false %>
<%= f.input :last_name, placeholder: 'Last name ', label: false%>
<%= f.input :street, placeholder: 'Street name', label: false %>
<%= f.input :street_number, placeholder: 'Street Number', label: false %>
<%= f.input :country, placeholder: 'Country', label: false %>
<%= f.input :zip_code, placeholder: 'Zip Code', label: false %>
<%= f.input :city, placeholder: 'City', label: false %>
<%= f.input :avatar, placeholder: 'Your avatar', as: :attachinary %>
  <%= f.submit profile_message, class: "btn rounded-camp" %>
<% end %>

app/views/profiles/edit.html.erb
<div class="bg-profile">
<div class="container">
  <div class="row">

    <div class="col-md-6 "></div>

      <div class="col-md-6 bg-profile-description">
        <div class="header-profile"></div>

        <ul>
         <%= render "form", profile_message: "Edit profil" %>
        </ul>
      </div>

    </div>
  </div>
</div>

app/views/profiles/new.html.erb
<div class="bg-profile">
  <div class="container">
    <div class="row">


      <div class="col-md-6 "></div>

      <div class="col-md-6 bg-profile-description">
        <div class="header-profile"></div>

        <ul>
         <%= render "form", profile_message: "Create profil" %>
       </ul>
     </div>

   </div>
 </div>
</div>

app/views/profiles/show.html.erb
<div class="bg-profile">
<div class="container">
  <div class="row">

    <div class="col-md-6 text-center"><% if @profile.avatar? %>
      <%= cl_image_tag @profile.avatar.path, class: "img-profile-page" %>
      <% end %></div>

      <div class="col-md-6 bg-profile-description">
        <div class="header-profile"><h2><%= @profile.first_name.capitalize %>: Profile </h2></div>

        <ul>
          <li><strong>Last Name:</strong> <%= @profile.last_name %></li>
          <hr>
          <li><strong>Street Name:</strong> <%= @profile.street %></li>
          <hr>
          <li><strong>Street Number:</strong> <%= @profile.street_number %></li>
          <hr>
          <li><strong>Zip Code:</strong> <%= @profile.zip_code %></li>
          <hr>
          <li><strong>City:</strong> <%= @profile.city %></li>
          <hr>
          <li><strong>Country:</strong> <%= @profile.country %></li>
        </ul>
      </div>
         <%= link_to "Update Profile", edit_profile_path(current_user.profile), class: "btn rounded-profile" %>
          <% if current_user.companies.empty? %>
          <%= link_to "Add company", new_company_path, class: "btn rounded-profile" %>
          <% else %>
          <%= link_to "Company", '/companies', class: "btn rounded-profile" %>
          <% end %>
    </div>
  </div>
</div>