config/routes.rb
Rails.application.routes.draw do

  get 'pages/privacypolicy'

  get 'previews/demo'

  root to: 'pages#home'

  mount Attachinary::Engine => "/attachinary"

  resources :profiles, except: [:destroy ]

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  resources :companies do
    resources :campaigns do
      post "/create_facebook_campaign",  to: "campaigns#create_facebook_campaign", as: "create_facebook"
      post "/create_facebook_adset", to: "campaigns#create_facebook_adset", as: "create_adset"
      resources :ads do
        post "create_facebook_ad", to: "ads#create_facebook_ad", as: "create_ad"
      end

    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links hidden-xs hidden-sm">
    <a href="#"><i class="fa fa-github"></i></a>
    <a href="#"><i class="fa fa-instagram"></i></a>
    <a href="#"><i class="fa fa-facebook"></i></a>
    <a href="#"><i class="fa fa-twitter"></i></a>
    <a href="#"><i class="fa fa-linkedin"></i></a>
    <%= link_to "Privacy policy", pages_privacypolicy_path %>
  </div>
  <div class="footer-copyright">
     <%= image_tag "logo-black.png", class: "brandsize"  %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo-black.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->

      <div class="navbar-wagon-item">
      <div class="dropdown">
      <% if current_user.profile.nil? %>
      <%= link_to "New Profile", new_profile_path, class: "rounded-camp-new-ad" %>
      <% else %>
      <%= link_to "Profile", profile_path(current_user.profile), class: "rounded-camp-new-ad" %>
      <% end %>
      <% if current_user.profile %>
        <% if current_user.companies.empty?  %>
          <%= link_to "Create company", new_company_path, class: " rounded-camp-new-ad" %>
        <% else  %>

          <%= link_to "Dashboard", '/companies', class: " rounded-camp-new-ad" %>

        <% end %>
      <% end %>




      </div>
      </div>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <% if current_user.nil? || current_user.profile.nil? %>
        <%= image_tag "logo-black.png", class: "avatar dropdown-toggle", id: "logo", data: { toggle: "dropdown" } %>
        <% elsif current_user.profile.avatar.nil?  %>
        <%= image_tag "logo-black.png", class: "avatar dropdown-toggle", id: "logo", data: { toggle: "dropdown" } %>
        <% else %>
        <%= cl_image_tag current_user.profile.avatar.path, class: "avatar dropdown-toggle", id: "logo", data: { toggle: "dropdown" } %>
        <% end %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">

            <li>
              <%= link_to root_path do %>
                <i class="fa fa-home"></i>  <%= t( "Home") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_navbarhome.html.erb
<nav class="navbar navbar-default navbar-fixed-top navbar-home">
  <div class="container-fluid ">
    <div class="navbar-header">
      <a class="navbar-brand " href="#">
        <%= image_tag "logo-white.png", class: "brandsize" %>
      </a>


  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "your company", "/companies", class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "campaigns", "/campaigns", class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Messages", "#", class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to destroy_user_session_path, method: :delete do %>
                <%= t(".sign_out", default: "Log out") %>
              <% end %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "http://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <% if current_user.profile.nil? %>
                <%= link_to "Profile", new_profile_path %>
              <% else %>
                <%= link_to "Profile", profile_path(current_user.profile) %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>

    </div>
  </div>
</div>

</nav>