config/routes.rb
Rails.application.routes.draw do

  get 'pages/privacypolicy'

  get 'previews/demo'

  root to: 'pages#home'

  mount Attachinary::Engine => "/attachinary"

  resources :profiles, except: [:destroy ]

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  resources :companies do
    resources :campaigns do
      post "/create_facebook_campaign",  to: "campaigns#create_facebook_campaign", as: "create_facebook"
      post "/create_facebook_adset", to: "campaigns#create_facebook_adset", as: "create_adset"
      resources :ads do
        post "create_facebook_ad", to: "ads#create_facebook_ad", as: "create_ad"
      end

    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/company.rb
class Company < ApplicationRecord
  belongs_to :user
  has_many :campaigns
  has_attachment :picture
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController

before_action :set_company, only: [:show, :edit, :update, :destroy]
skip_before_action :authenticate_user!, only: :index


  def index
    @companies = current_user.companies
  end


  def show
  end

  def new
    @company = Company.new
  end

  def create
    @company = Company.new(company_params)
    @company.user = current_user
    @company.save!
    redirect_to company_path(@company)
  end

  def edit
  end

  def update
    @company.update(company_params)
    redirect_to company_path(@company)
  end

  def destroy
    @company.destroy
    redirect_to companies_path
  end


  private

  def set_company
    @company = Company.find(params[:id])
  end

  def company_params
    params.require(:company).permit(:name, :street, :street_number, :city, :country, :email, :picture)
  end

end

app/views/companies/_form.html.erb
  <div class="bg-campaign-inside">
  <h4><%= current_user.profile.first_name %> <%= current_user.profile.last_name %></h4>
</div>
<%= simple_form_for [@company] do |f| %>
<div class="col-md-6 bg-campaign-inside2">
  <%= f.input :name, label: "Name of the company or subsidiary" %>
  <%= f.input :street_number %>
  <%= f.input :street %>
  <%= f.input :picture, as: :attachinary %>
</div>
<div class="col-md-6 bg-campaign-inside3">
  <%= f.input :city %>
  <%= f.input :country %>
  <%= f.input :email %>
  <%= f.submit company_message, class: "btn rounded-camp" %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<div class="bg-company">
<div class="container">
  <div class="row">
<br>

         <%= render "form", company_message: "Create a new Company" %>



    </div>
  </div>
</div>

app/views/companies/index.html.erb
<%#= render "form", company_message: "Adit this Company info" %>

<div class="bg-company">
  <div class="container">
    <div class="row">
      <div class="col-md-12 padtopcamp">
        <ul class="list-inline product-controls">
          <li><%= link_to "Add company", new_company_path, class: " rounded-camp-head" %></li>
        </ul>
        <br>
        <% @companies.each do |company| %>

        <div class="product padbottomcamp">
          <div class='product-upvote'>
            <div class="product-arrow"></div>
            <div class='product-count'><%= company.id %></div>

          </div>
          <% if company.picture? %>
            <%= cl_image_tag company.picture.path, width: "300px", height: "200px" %>
          <% else %>
            <%= image_tag("netw.png", class: "product-image hidden-xs") %>
          <% end %>
          <div class='product-body'>
           <h4><%= company.name %></h4>
           <p><%= company.street_number %> <%= company.street %></p>
         </div>
         <div class='product-body'>
          <p><%= company.city %></p>
          <p><%= company.country %></p>
          <p><%= company.email %></p>
        </div>
      </div>
      <div class="container-fluid">
          <div class="row paddingbottom">
    <div class="col-md-6">
      <ul class="list-inline product-controls">
        <% if current_user.companies.any? %>
        <li><%= link_to "Edit company", edit_company_path(company), class: "btn rounded-camp" %>
         <li><%= link_to "Delete the company", company_path(company) , class: "btn rounded-camp", method: :delete, data: { confirm: 'Are you certain you want to delete this?' } %></li>
       </ul>
     </div>
     <div class="col-md-6">
      <ul class="list-inline product-controls">
       <% if company.campaigns.empty? %>
       <li><%= link_to 'Create campaigns', new_company_campaign_path(company), class: "btn rounded-camp"  %></li>
       <% else %>
       <li><%= link_to 'See all my campaigns', company_campaigns_path(company), class: "btn rounded-camp"%></li>
       <% end %>
       <% end %>
     </ul>
   </div>
</div>
</div>

   <% end %>
 </div>
 <hr>


</div>
</div>
</div>

app/views/companies/new.html.erb
<div class="bg-company">
<div class="container">
  <div class="row">

<%= render "form", company_message: "Create a new Company" %>

  </div>
</div>
</div>

app/views/companies/show.html.erb
<div class="bg-company">
  <div class="container">
    <div class="row">
      <div class="col-md-4 bg-profile-description">
        <div class="header-profile"></div>
        <div class="card" style="background-image: linear-gradient(rgba(0,0,0,-29.7), rgba(0,0,0,9.2)), url(<%=  @company.picture? ? (cl_image_path @company.picture.path) : (image_path 'lokoshop-8.jpg'); %>);">
          <div class="card-category"> <h4><%= @company.name %></h4>
          </div>
          <div class="card-description">

            <p><%= @company.street_number%> -
            <%= @company.street%> -
            <%= @company.city%></p>
            <p><%= @company.email%></p>
          </div>

        </div>
        <br>
        <%= link_to "Create a new local Ad!",  new_company_campaign_path(company_id: @company.id), class: "btn rounded-camp" %>

      </div>

    </div>
  </div>
</div>