config/routes.rb
Rails.application.routes.draw do

  get 'pages/privacypolicy'

  get 'previews/demo'

  root to: 'pages#home'

  mount Attachinary::Engine => "/attachinary"

  resources :profiles, except: [:destroy ]

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  resources :companies do
    resources :campaigns do
      post "/create_facebook_campaign",  to: "campaigns#create_facebook_campaign", as: "create_facebook"
      post "/create_facebook_adset", to: "campaigns#create_facebook_adset", as: "create_adset"
      resources :ads do
        post "create_facebook_ad", to: "ads#create_facebook_ad", as: "create_ad"
      end

    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/campaign.rb
class Campaign < ApplicationRecord
  has_attachments :photos, maximum: 5
  belongs_to :company
  validates :campaign_objective, presence: true
  validates :campaign_name, presence: true
  # after_create :send_launch_campaign_email
  # after_update :send_update_email
  has_many :ads

  private

  # def send_launch_campaign_email
  #   CampaignMailer.launch_campaign(self).deliver_now
  # end

  # def send_update_email
  #   CampaignMailer.update_campaign(self).deliver_now
  # end

end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController

  # require 'facebook_ads'

  before_action :set_company, only: [:index, :new, :create, :show, :edit, :update]
  before_action :set_campaign, only: [:show, :edit, :update]
  before_action :set_campaign_by_campaign_id, only: [:create_facebook_campaign]

  include FacebookAdsHelper

 def index
    @campaigns = @company.campaigns
    # @created_campaigns = Campaign.where(user: current_user)
    # raise
  end

  def new
    @campaign = Campaign.new
  end

  def create
    @campaign = Campaign.new(campaign_params)
    @campaign.company = @company
    if @campaign.save!
      flash[:notice] = "Campaign #{@campaign.campaign_name} created!"
      redirect_to company_campaign_path(@company, @campaign)
    else
      render :new
    end
  end

  def create_facebook_campaign
    # create campaign
    campaign_details = {
      name: @campaign.campaign_name,
      objective: @campaign.campaign_objective
    }
    fb_campaign = create_fb_campaign(campaign_details) # <-- This is the Facebook helper
    # create adset
    adset_details = {
      fb_id: fb_campaign[:id],
      adset_name: @campaign.adset_name,
      # start: @campaign.adset_start_date,
      # end: @campaign.adset_end_date,
      adset_bid_amount: @campaign.adset_bid_amount,
      adset_billing_event: @campaign.campaign_objective,
      adset_daily_budget: @campaign.adset_daily_budget,
      campaign_id: @campaign.id,
      adset_age_min: @campaign.adset_age_min,
      adset_age_max: @campaign.adset_age_max,
      adset_location: @campaign.adset_location
    }
    create_adset(adset_details) # <-- This is the Facebook helper facebook_ads_helper.rb
    redirect_back(fallback_location: company_campaign_path(@campaign.company, @campaign))
  end


  # def create_facebook_adset
  #   adset_details = {
  #     name: @campaign.adset_name,
  #     start: @campaign.adset_start_date,
  #     end: @campaign.adset_end_date,
  #     bid_amount: @campaign.adset_bid_amount,
  #     billing: @campaign.adset_billing_event,
  #     budget: @campaign.adset_daily_budget,
  #     campaign_id: @campaign.id
  #   }
  #   create_adset(adset_details) # <-- This is the Facebook helper facebook_ads_helper.rb
  #   redirect_back(fallback_location: company_campaign_path(@campaign.company, @campaign))
  # end

  def show
    # from facebook helper:
    @fb_campaign = show_fb_campaign(@campaign.campaign_name)
  end

  def edit
  end

  def update
    @campaign.update(campaign_params)
    redirect_to company_booking_path(@company, @campaign)
  end


  private

  def set_company
    @company = Company.find(params[:company_id])
  end

  def set_campaign
    @campaign = Campaign.find(params[:id])
  end
  def set_campaign_by_campaign_id
    @campaign = Campaign.find(params[:campaign_id])
  end

  def campaign_params
    params.require(:campaign).permit(:campaign_name, :campaign_objective, :adset_name, :adset_bid_amount, :adset_billing_event, :adset_daily_budget, :adset_age_min, :adset_age_max, :adset_location)
  end
end

app/views/campaigns/_form.html.erb
<br>
<div class="col-sm-6 col-xs-12">
  <div class="bg-campaign-inside">
  <h4>Objective</h4>
  <%= simple_form_for [@company, @campaign] do |f| %>
  <%= f.input :campaign_name, placeholder: "Name of your campaign", label: "Campaign Name"  %>
  <%= f.input :campaign_objective, collection: ['LINK_CLICKS', 'APP_INSTALLS', 'IMPRESSIONS', 'OFFER_CLAIMS', 'PAGE_LIKES', 'POST_ENGAGEMENT', 'VIDEO_VIEWS', 'TWO_SECOND_CONTINUOUS_VIDEO_VIEWS', 'COMPLETED_VIDEO_VIEWS', 'VIDEO_VIEWS_15S'], selected: 1, label: "Type of campaign : per click, per display, etc."  %>

  <%= f.input :adset_name, placeholder: "Targeted audience", label: "Define your targeted audience"  %>
  </div>
</div>
<div class="col-sm-6 col-xs-12 pull-right">
  <div class="bg-campaign-inside2">
  <h4>Budget & Audience</h4>
  <%= f.input :adset_bid_amount, placeholder: "Enter amount in cents", label: "Budget per click or 1000 displays" %>
  <%= f.input :adset_daily_budget, placeholder: "Enter amount in cents", label: "Budget per day" %>
  <%= f.input :adset_age_min, placeholder: "Minimum Age", label: "Minimum age of your audience"  %>
  <%= f.input :adset_age_max, placeholder: "Maximum Age", label: "Maximum age of your audience"  %>
  <%= f.input :adset_location, collection: ["BE", "FR", "AU", "GB", "NZ", "US", "NL"], selected: 1, prompt: "Select participation country", label: "Country targeted"  %>
<%= f.submit 'Start my campaign', class: "btn rounded-camp" %>
  <% end %>
</div>
</div>

app/views/campaigns/index.html.erb
  <div class="bg-company">
    <div class="container">
      <div class="row">

        <div class="message-status2" style="margin-top: 20px;">
          <h3><%= @company.name %></h3>
          <%= link_to 'Create a new Campaign (Audience and Budget)', new_company_campaign_path(@company), class: " quad-camp-new-ad-blue"%>

        </div>
        <% @campaigns.each do |campaign| %>
        <hr>

        <div class="col-sm-12 col-md-12">


          <div class="row">
            <div class="message">
              <div class="col-xs-6 col-sm-6 col-md-3">
                <div class="message-status2">
                <p> <%= link_to 'See all my Ads!', company_campaign_path(campaign.company, campaign), class: "btn rounded-camp-new-ad-blue"%></p><br>
                 <p> <%= link_to 'Create a new Ad!', new_company_campaign_ad_path(campaign.company, campaign), class: "btn rounded-camp-new-ad-red"%></p>
                </div>

              </div>
              <div class=" col-xs-6 col-sm-6 col-md-3">
                <div class="message-name">
                  <p>Campaign n° :: <%= campaign.id %></p>
                  <h2><%= campaign.campaign_name %></h2>
                  <h3>Audience :: <%= campaign.adset_name%></h3>

                </div>
              </div>
              <div class=" col-xs-6 col-sm-6 col-md-3 hidden-xs hidden-sm">
                <div class="message-body">
                  <p>Type of Campaign :: <%= campaign.campaign_objective %></p>
                  <p>Period :: Continuous </p>
                </div>
              </div>
              <div class="col-xs-6 col-sm-6 col-md-2">
                <div class="message-status">
                  <p class="status pending"><%= campaign.adset_bid_amount.to_i / 100 %> € / click </p>
                  <p class="price"><%= campaign.adset_daily_budget.to_i / 100 %> € / day</p>
                  <p></p>

                </div>
              </div>
              <div class="col-md-2 hidden-xs hidden-sm">

                <img class="avatar-small" src="/assets/lokoshop-8.jpg">


              </div>
            </div>
          </div>

        </div>
        <% end %>
      </div>
    </div>
  </div>

app/views/campaigns/new.html.erb
<div class="bg-campaigns">
<div class="container">
  <div class="row">

    <%= render "form", campaign_message: "Create a new campaign" %>
  </div>
</div>
</div>

app/views/campaigns/show.html.erb
<div class="bg-dashboard">
  <div class="container">
    <div class="row">
      <div class="col-md-12 dashboard-padding">
        <div class="row">
          <div  class="col-md-6">
            <div class="inside-dashboard-bg">
             <%= link_to 'Create a new Ad!', new_company_campaign_ad_path(@campaign.company, @campaign), class: "btn quad-camp-new-ad"%>
             <h3> <%= @campaign.company.name %> </h3>
             <h4><%= @campaign.campaign_name %></h4>
             <p>Type of Campaign : <%= @campaign.campaign_objective %></p>
             <hr>
             <h4>Audience</h4>
             <p><%= @campaign.adset_name %></p>
             <p>From <%= @campaign.adset_age_min %> to <%= @campaign.adset_age_max %> years old</p>
             <p>Country <%= @campaign.adset_location %></p>

             <!-- CSS Grid Layout browser support text -->
             <hr>
             <h4>Budget</h4>
             <p> <%= @campaign.adset_bid_amount.to_i / 100 %> € / click </p>
             <p> <%= @campaign.adset_daily_budget.to_i / 100 %> € / day</p>
             <hr>
           </div>
          </div>
          <br>
          </ul>

        <div class="col-md-6">
           <% if @fb_campaign != [] %>
           <div class="formfb-ads">
            <ul>
              <li><h4> Facebook Ad</h4></li>
              <% if @fb_campaign != [] %>
              Status : PAUSED
              <% else %>
              Status : LIVE
              <% end %>
              <p>Objective: <%= @campaign.campaign_objective %></p>
              <hr>
              <h4>Audience</h4>
              <p>Ages:<%= @campaign.adset_age_min %> to <%= @campaign.adset_age_max %></p>
              <p><%= @campaign.adset_location %></p>
            </div>
          <% else %>
            <%= button_to "Launch your campaign", company_campaign_create_facebook_path(@company, @campaign), method: :post, class: ' rounded-camp-new-ad-red' %>
          <% end %>
        <% if @campaign.ads.any? %>
          <div class="facebook-font">Running facebook ads</div>
          <% @campaign.ads.each do |ad| %>
          <%= render 'ad-preview', ad: ad %>
          <% end %>
        <% end %>
        </div>

          <div class="col-sm-6 col-sm-offset-2 col-xs-12 ">
            <%= link_to 'All my campaigns', company_campaign_path(@campaign.company, @campaign), class: 'btn rounded-camp-new-ad-red' %>
            <br>
        </div>
      </div>
    </div>
  </div>
</div>
</div>